const doubloonImg = '<img src="assets/doubloon.svg" alt="Doubloon Icon" class="doubloon"/>';
// prettier-ignore
const doubloonShop = {
  "Pile of Stickers": 17,
  "OpenAI credits": 28,
  "Hetzner credits": 28,
  "Anthropic Credits": 28,
  "Heroku Credits": 28,
  "Hack Club MicroSD card": 30,
  "Logic Analyzer": 34,
  "McMaster-Carr Credits": 38,
  "iFixit Credits": 38,
  "Bite Size Linux": 40,
  "Bite Size Bash": 40,
  "How DNS Works": 40,
  "Domain (1 year)": 40,
  "How Git Works": 40,
  "Hell Yes! CSS!": 40,
  "Signed photo of Malted": 42,
  "The Pocket Guide to Debugging": 50,
  "Digital Calipers": 50,
  "PCB manufacturing credit!": 55,
  "Adafruit ItsyBitsy M4 Express": 55,
  "Hot Glue Gun": 57,
  "DigiKey/LCSC Credit": 63,
  "Raspberry Pi": 73,
  "GitHub Invertocat Pin!": 76,
  "Signed photo of Graham Darcey": 80,
  "c u b e": 110,
  "Pinecil": 120,
  "GitHub Notebook": 120,
  "Blåhaj": 123,
  "Baofeng UV-5R": 126,
  "Lockpick set": 151,
  "GitHub Keycaps": 154,
  "Hack Club socks!": 156,
  "Factorio": 170,
  "GitHub Universe Badge": 172,
  "1 lb fudge from place next to HQ": 220,
  "YubiKey": 264,
  "Dremel 4300 kit": 265,
  "Raspberry Pi 5": 265,
  "Logitech MX Master 3S": 480,
  "GitHub Stanley Tumbler": 500,
  "Blot": 675,
  "GitHub MiiR® Backpack": 725,
  "System76 Launch Keyboard": 790,
  "Flipper": 850,
  "Ben Eater 8-bit computer kit": 975,
  "Bambu Lab A1 Mini": 1000,
  "Thermal imaging camera": 1015,
  "Hot-air rework station": 1120,
  "100MHZ Oscilloscope": 1210,
  "iPad": 2090,
  "Mac M4 Mini": 2400,
  "Framework Laptop 13": 3075,
  "MacBook Air M2 13": 4000,
  "Framework Laptop 16": 4980,
  "ticket to DEF CON": 6675
};

const colorToggleableElements = [
  "--background-color",
  "--text-color",
  "--secondary-text-color",
  "--hover-div-color",
  "--input-color",
];

export { doubloonImg, doubloonShop, colorToggleableElements };
